version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/home/app/web/
      - static:/static
      - media:/media
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$SQL_HOST/$POSTGRES_DB
    env_file:
      - ./.env

  redis:
    image: redis:alpine

  cache:
    image: memcached:alpine

volumes:
  postgres_data:
  static:
  media:
