version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/home/app/web/
      - static:/static
      - media:/media
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$SQL_HOST/$POSTGRES_DB
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`mv.dev.digitalorganizing.ch`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=8000"

  redis:
    image: redis:alpine

  cache:
    image: memcached:alpine

volumes:
  postgres_data:
  static:
  media:

networks:
  web:
    external: true

