# Generated by Django 4.1.4 on 2022-12-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('min_amount_for_dispute_raise', models.FloatField()),
                ('min_amount_for_dispute_reduction', models.FloatField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.section')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('allg_kostensteigerung_type', models.CharField(choices=[('rechner', 'Gemäss Rechner'), ('pauschal', 'Pauschal')], max_length=120)),
                ('allg_kostensteigerung_value', models.FloatField()),
                ('is_landloard_required', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.address')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.section')),
            ],
        ),
    ]
